name: frontend

on:
  push:
    branches: ['karsajobs-ui']
  pull_request:
    branches: ['karsajobs-ui']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: lint-Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: build-app-karsajobs-ui
        run: ./build_push_image_karsajobs_ui.sh
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
